### ISSUE TITLE
فایرفاکس اندروید

### ISSUE THREAD

**Issue by xmha97** [Mohsen-ED/cafabazaar-apk-downloader-firefox#1]
سلام، من این add-ons را روی فایرفاکس اندروید نصب کردم.
دکمه‌ی دانلود در حالت desktop site نمایش داده میشه اما در حالت کلی، نه.

**Comment by Ya-Zahra** [comment]
سلام، طراحی اولیه افزونه برای کار بر روی مروگر رایانه های شخصی بوده.
من فعلا راهی برای نصب افزونه بر روی فایرفاکس اندروید پیدا نکردم تا بتوانم آن را اشکال زدایی کنم.
خوشحال میشوم راهی که افزونه را روی اندروید نصب کرده اید به من اطلاع بدهید. باتشکر از توجه شما

**Comment by xmha97** [comment]
فقط در نسخه‌ی Nightly فایرفاکس این قابلیت فعال است.
https://play.google.com/store/apps/details?id=org.mozilla.fenix

طبق این آموزش پیش برید، سوال داشتید، بپرسید.
https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by Ya-Zahra** [comment]
تشکر از راهنمایی شما 🙏
بررسی میکنم.

**Comment by xmha97** [comment]
سلام، آیا تونستید روی فایرفاکس اندروید افزونه نصب کنید؟

**Comment by Ya-Zahra** [comment]
سلام، بله موفق شدم و یک مشکل اساسی را حل کردم اما به یک باگ دیگه خوردم که در حال تست هستم.
مشکل ظاهرا از فرانت کافه بازار نسخه موبایل هست که درحال بررسی هستم.

**Comment by xmha97** [comment]
ممنون از پیگیری‌تون، ان‌شاءالله که نتیجه بده.

**Comment by Ya-Zahra** [comment]
سلام، به توفیق الهی و با عنایات حضرت زهرا سلام الله علیها مشکل ظاهرا برطرف شد. نسخه جدید منتشر شد.
باز هم تشکر از شما 🙏

**Comment by xmha97** [comment]
> سلام، به توفیق الهی و با عنایات حضرت زهرا سلام الله علیها مشکل ظاهرا برطرف شد. نسخه جدید منتشر شد.
> باز هم تشکر از شما 🙏

سلام علیکم، ضمن قبولی طاعات و عبادات شما از پشتیبانی از فایرفاکس اندروید نهایت قدردانی را به عمل می‌آورم. 🙏🌹

![Screenshot_2023-04-03-05-01-21-826_org.mozilla.fenix.jpg](https://user-images.githubusercontent.com/23485114/229392244-7e283ba7-ea9f-4d5f-8f49-acfe3fedf34a.jpg)

**Comment by xmha97** [comment]
ببخشید امکان دارد افزونه مایکت رو هم سازگار با فایرفاکس اندروید کنید؟

همچنین امکان دارد به من پیام بدید؟

[+989360539854](tel:+989360539854)
[eitaa.com/xmha970](eitaa.com/xmha970)
[t.me/id1296923023](t.me/id1296923023)

**Comment by Ya-Zahra** [comment]
سلام علیکم، از لطف و محبت شما بسیار سپاسگزارم.
متشکرم، طاعات و عبادات شما هم قبول باشه.
از آشنایی با دوست خوبی همچون شما خرسندم.
ممنون از تصویر خوبی که ضمیمه کردید.
بله، ان شاء الله اگر یک مقدار فرصت بیشتر پیدا کنم روی افزونه مایکت هم کارخواهم کرد.
به شناسه کاربریتون داخل ایتا پیام دادم.

**Comment by xmha97** [comment]
ممنون از شما
